# Generated by Django 5.2.1 on 2025-07-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'get_latest_by': '-pk', 'verbose_name': 'Round', 'verbose_name_plural': 'Rounds'},
        ),
        migrations.AddField(
            model_name='round',
            name='state',
            field=models.CharField(choices=[('P', 'Programmed'), ('O', 'Ongoing'), ('C', 'Completed')], default='P'),
        ),
    ]
