# Generated by Django 5.2.1 on 2025-06-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0003_standing_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='games_tied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='matches_tied',
            field=models.IntegerField(default=0),
        ),
    ]
