# Generated by Django 5.2.1 on 2025-06-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0004_standing_games_tied_standing_matches_tied'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standing',
            options={'ordering': ['-tournament', '-matches_won', '-games_won', '-opponents_match_winrate', '-opponents_game_winrate'], 'verbose_name': 'Standing', 'verbose_name_plural': 'Standings'},
        ),
        migrations.AlterModelTable(
            name='standing',
            table='standings',
        ),
    ]
