# Generated by Django 5.2.1 on 2025-06-22 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0006_opponentstracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opponentstracker',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='opponents', to='standings.standing'),
        ),
        migrations.AlterField(
            model_name='opponentstracker',
            name='standing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponents_tacker', to='standings.standing'),
        ),
    ]
