# Generated by Django 5.2.1 on 2025-06-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0007_alter_opponentstracker_opponent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standing',
            options={'ordering': ['-points', '-matches_won', '-games_won', '-opponents_match_winrate', '-opponents_game_winrate'], 'verbose_name': 'Standing', 'verbose_name_plural': 'Standings'},
        ),
    ]
