# Generated by Django 5.2.1 on 2025-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='ongoing',
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('P', 'Programmed'), ('O', 'Ongoing'), ('C', 'Completed')], default='P'),
        ),
    ]
