# Generated by Django 5.2.1 on 2025-06-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('tournaments', '0004_rename_status_tournament_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_won', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='players.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Standing',
                'verbose_name_plural': 'Standings',
            },
        ),
    ]
