# Generated by Django 5.2.1 on 2025-06-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='opponents_game_winrate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='standing',
            name='opponents_match_winrate',
            field=models.FloatField(default=0),
        ),
    ]
