# Generated by Django 5.2.1 on 2025-06-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0002_standing_matches_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
