# Generated by Django 5.2.1 on 2025-06-22 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_name'),
        ('rounds', '0001_initial'),
        ('standings', '0005_alter_standing_options_alter_standing_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpponentsTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='appearences', to='players.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponents_trackers', to='rounds.round')),
                ('standing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponents', to='standings.standing')),
            ],
            options={
                'verbose_name': 'OpponentsTracker',
                'verbose_name_plural': 'OpponentsTrackers',
                'db_table': 'opponents_trackers',
            },
        ),
    ]
