# Generated by Django 5.2.1 on 2025-07-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0008_alter_standing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standing',
            options={'ordering': ('-points', '-matches_won', '-games_won', '-opponents_match_winrate', '-opponents_game_winrate'), 'verbose_name': 'Standing', 'verbose_name_plural': 'Standings'},
        ),
    ]
