# Generated by Django 5.2.1 on 2025-06-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerentry',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
