# Generated by Django 5.2.1 on 2025-05-22 13:29

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('number_of_rounds', models.IntegerField(null=True)),
                ('ongoing', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(to='players.player')),
            ],
            options={
                'verbose_name_plural': 'tournamens',
                'db_table': 'tournaments',
                'ordering': ['-created'],
                'get_latest_by': '-created',
            },
        ),
    ]
