# Generated by Django 5.2.1 on 2025-07-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('S', 'Simple')], default='S'),
        ),
    ]
