# Generated by Django 5.2.1 on 2025-07-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'get_latest_by': '-created', 'ordering': ('-created',), 'verbose_name_plural': 'tournaments'},
        ),
    ]
