# Generated by Django 5.2.1 on 2025-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_placeholder', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'players',
                'db_table': 'players',
                'ordering': ['name'],
            },
        ),
    ]
