# Generated by Django 5.2.1 on 2025-07-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('name',), 'verbose_name_plural': 'players'},
        ),
    ]
