# Generated by Django 5.2.1 on 2025-06-09 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='rounds.round')),
            ],
            options={
                'verbose_name': 'Pairing',
                'verbose_name_plural': 'Pairings',
            },
        ),
        migrations.CreateModel(
            name='PlayerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pairings.pairing')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pairings', to='players.player')),
            ],
            options={
                'verbose_name': 'Pairing',
                'verbose_name_plural': 'Pairings',
                'db_table': 'player_pairings',
            },
        ),
    ]
